blank_issues_enabled: false
contact_links:
  - name: Tasks to create new or modify existing documentation
    url: https://github.com/openhwgroup/core-v-docs/blob/master/.github/ISSUE_TEMPLATE/task.md
    about: Please ask and answer questions here.
  - name: Bugs against existing documentation
    url: https://github.com/openhwgroup/core-v-docs/blob/master/.github/ISSUE_TEMPLATE/doc_bug.md
    about: Please report security vulnerabilities here.
