blank_issues_enabled: false
contact_links:
  - name: Tasks
    url: https://github.com/openhwgroup/core-v-docs/issues/new?template=task.md
    about: Tasks to create new or modify existing documentation.
  - name: Bugs
    url: https://github.com/openhwgroup/core-v-docs/issues/new?template=doc_bug.md
    about: Bugs against existing documentation.
